version: "2"
exclude_patterns:
- "public"
- "database"
- "app/Console"
# Nilai F
- "app/Http/Controllers/V1/ValidasiController.php"
- "app/Http/Controllers/V1/VerifikasiController.php"
- "app/Http/Controllers/V1/RegisterController.php"
- "app/Http/Controllers/RegistrasiMandiri.php"
- "app/Http/Controllers/V1/PCRController.php"
- "app/Http/Controllers/V1/DashboardController.php"
- "app/Http/Controllers/V1/EkstraksiController.php"
- "app/Http/Controllers/SampleController.php"
# Nilai D
- "app/Http/Controllers/V1/PelacakanSampelController.php"
- "app/Http/Controllers/V2/PelacakanSampelController.php"
- "app/Http/Controllers/V2/PCRController.php"
- "app/Http/Controllers/RegistrasiRujukanController.php"
- "app/Http/Controllers/V2/EkstraksiController.php"
- "routes/api.php"
# Nilai C
- "app/Http/Controllers/V2/DashboardController.php"
- "app/Http/Controllers/V1/ReagenEkstraksiController.php"
- "app/Http/Controllers/V1/TesMasifController.php"
- "app/Imports/RegisterRujukanImport.php"
- "app/Imports/HasilPemeriksaanImport.php"
